language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

before_script:
  - composer install

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true
